server:
  port: ${PORT:8080}
spring:
  application:
    name: taskManager
  liquibase:
    enabled: true
  output:
    ansi:
      enabled: always
  mvc:
    hiddenmethod:
      filter:
        enabled: true
base-url: /api
rollbartoken: ${ROLLBAR_TOKEN}









