server:
  port: ${PORT:8080}
  servlet:
    context-path: /api
logging:
  level:
    root: INFO
spring:
  application:
    name: taskManager
  liquibase:
    enabled: true
  output:
    ansi:
      enabled: always
sentry:
  dsn: https://examplePublicKey@o0.ingest.sentry.io/0
  tracesSampleRate: 1.0

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem









